name: Build and deploy .NET application to Azure Container Apps

on:
  push:
    branches:
    - deploy
    
env:
  
  # alphanumeric string under 14 characters
  RESOURCE_GROUP_NAME: containerapp

  # specify your preferred region
  REGION: westus

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-dev-cli-apps:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in with Azure (Client Credentials)
        env:
          AZURE_TENANTID1: ${{ secrets.TENANTID }}
          AZURE_CLIENTID1: ${{ secrets.CLIENTID }}
          AZURE_CLIENTSECRET1: ${{ secrets.CLIENTSECRET }}
          AZURE_AZ_LOGIN: ${{ secrets.AZ_LOGIN }}
        run: azd login --no-prompt $Env:AZURE_AZ_LOGIN 
        shell: pwsh              
             
      - name: Azure Dev Provision
        run: azd provision --no-prompt
        env:
          AZURE_ENV_NAME: ${{ env.RESOURCE_GROUP_NAME }}
          AZURE_LOCATION: ${{ env.REGION }} 
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure Dev Deploy
        run: azd deploy --no-prompt
        env:
          AZURE_ENV_NAME: ${{ env.RESOURCE_GROUP_NAME }}
          AZURE_LOCATION: ${{ env.REGION }} 
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

